apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mijn-kia.fullname" . }}
  labels:
    {{- include "mijn-kia.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mijn-kia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mijn-kia.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /MijnKia/MijnKia.ini
              subPath: MijnKia.ini
              name: mijn-kia-ini
      volumes:
        - name: mijn-kia-ini
          configMap:
            name: mijnkia-ini
            items:
              - key: MijnKia.ini
                path: MijnKia.ini