# Default values for mijn_kia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ralphsmeets/mijn-kia-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.18.0

imagePullSecrets:
  - name: dockerhub

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

mijnKia:
  loginEmail: "user@domain.com"
  loginPassword: "myPassword"
  preferredVehicleId: 123456

aBetterRoutePlanner:
    token: "deadbeaf-dead-beef-dead-beefdeadbeaf"
    carModel: "brand:model:12:34:other"